<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <ClInclude Include="$(T850SourceRoot)T8ditor\include\t8ditor\EditorHost.h" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\main.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\EditorExtensions.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\EditorApp.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\EditorTutorialCapture.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\EditorCamera.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\EditorLineRenderer.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\EditorGrid.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\EditorGizmo.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\EditorMesh.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\EditorScene.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\EditorSceneGizmos.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\EditorMath.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\EditorUtil.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\EditorViewportUtil.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\HostedViewportPanel.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\EditorWorld.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\PlayScenePanel.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\MeshEditorPanel.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\RagdollEditorPanel.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\EditorImGui.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\..\DayScene\RagdollEditor.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\..\DayScene\Quake3Mock.cpp" />
    <ClCompile Include="$(T850SourceRoot)T8ditor\..\DayScene\SceneTemplate.cpp" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\EditorApp.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\EditorCamera.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\EditorLineRenderer.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\EditorGrid.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\EditorGizmo.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\EditorMesh.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\EditorScene.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\EditorSceneGizmos.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\EditorMath.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\EditorUtil.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\EditorViewportUtil.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\HostedViewportPanel.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\EditorSceneSerialization.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\EditorWorld.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\EditorInternal.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\EditorRagdollSupport.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\SceneObject.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\SceneGraph.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\UndoRedo.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\EditorImGui.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\..\DayScene\RagdollEditor.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\..\DayScene\Quake3Mock.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\..\DayScene\SceneTemplate.h" />
    <ClInclude Include="$(T850SourceRoot)T8ditor\..\DayScene\SandboxRenderGraphUtils.h" />
  </ItemGroup>
</Project>